version: 2.1

refs:
  - &only_master
    filters:
      branches:
        only: master

  - &not_master
    filters:
      branches:
        ignore: master

workflows:
  version: 2
  all:
    jobs:
      - all:
          <<: *not_master
          context: tokens
  master:
    jobs:
      - publish:
          <<: *only_master
          context: tokens

jobs:
  all:
    executor: node
    steps:
      - setup
      - build
      - test

  publish:
    executor: node
    steps:
      - setup
      - build
      - test

executors:
  node:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo

commands:
  setup:
    description: Checkout and install dependencies
    steps:
      - checkout
      - run:
          name: Versions
          command: node -v && npm -v && yarn -v
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

  build:
    steps:
      - run:
          name: Build
          command: yarn build
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Prettier (check "yarn prettier:write" has been run)
          command: yarn prettier:check

  test:
    steps:
      - run:
          name: Test
          command: yarn ci:test
